# Allows the running of the site in a subdirectory on Github Pages
# Note - if you enable this, and attempt to view your site locally you have to 
# pass the  --baseurl parameter when serving as an empty string e.g jekyll serve --baseurl ''
# http://jekyllrb.com/docs/github-pages/
baseurl : ""

# General settings
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

gems:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: "css"
    values:
      layout: "subpage"
      group: "css"
      navgroup: "css"
      type: "pages"
  -
    scope:
      path: "javascript"
    values:
      layout: "subpage"
      group: "javascript"
      navgroup: "javascript"
      type: "pages"

# Name of the website
name: Responsive

# Server
exclude:          ["CNAME","node_modules","Gemfile*"]

# Meta Details
description: A super lightweight HTML, Sass, CSS, and JavaScript framework for building responsive websites.
keywords: "HTML, Sass, CSS, JS, JavaScript, framework, responsive, rwd, front-end, frontend, web development, boilerplate"
author: "James South, and Responsive contributers"



# Custom variables
version: 4.0.0
buildsize : 27.7
repo: https://github.com/responsivebp/responsive
sourcefiles: https://github.com/ResponsiveBP/Responsive/archive/4.0.0.zip
release: https://github.com/ResponsiveBP/Responsive/releases/download/4.0.0/responsive.zip

