# Allows the running of the site in a subdirectory on Github Pages
# Note - if you enable this, and attempt to view your site locally you have to 
# pass the  --baseurl parameter when serving as an empty string e.g jekyll serve --baseurl ''
# http://jekyllrb.com/docs/github-pages/
baseurl : ""

relative_permalinks: false

# Name of the website
name: Responsive

# Server
exclude:          ["CNAME"]

# Meta Details
description: A super lightweight HTML, CSS, and JavaScript framework for building responsive websites.
keywords: "HTML, CSS, JS, JavaScript, framework, responsive, rwd, front-end, frontend, web development, boilerplate"
author: "James South, and Responsive contributers"



# Custom variables
version: 2.3.3
buildsize : 20.5
repo: https://github.com/responsivebp/responsive
release: https://github.com/ResponsiveBP/Responsive/releases/download/2.3.3/responsive.zip

