# Allows the running of the site in a subdirectory on Github Pages
# Note - if you enable this, and attempt to view your site locally you have to 
# pass the  --baseurl parameter when serving as an empty string e.g jekyll serve --baseurl ''
# http://jekyllrb.com/docs/github-pages/
baseurl : ""

markdown: kramdown

relative_permalinks: false

# Name of the website
name: Responsive

# Server
exclude:          ["CNAME","node_modules","Gemfile","Gemfile.lock"]

# Meta Details
description: A super lightweight HTML, Sass, CSS, and JavaScript framework for building responsive websites.
keywords: "HTML, Sass, CSS, JS, JavaScript, framework, responsive, rwd, front-end, frontend, web development, boilerplate"
author: "James South, and Responsive contributers"



# Custom variables
version: 3.1.4
buildsize : 25.5
repo: https://github.com/responsivebp/responsive
sourcefiles: https://github.com/ResponsiveBP/Responsive/archive/3.1.4.zip
release: https://github.com/ResponsiveBP/Responsive/releases/download/3.1.4/responsive.zip

